/*
 * La Caverne Malgache API
 * Documentation OpenAPI de La Caverne Malagasy. Couvre l'ensemble des ressources : utilisateurs, catalogue, commandes, paiements, livraisons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.Error;
import org.openapitools.client.model.LoginRequest;
import org.openapitools.client.model.LoginResponse;
import org.openapitools.client.model.RegisterRequest;
import org.openapitools.client.model.User;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AuthApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public AuthApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AuthApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for authLoginPost
     * @param loginRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Access JWT retourné dans le corps. Les cookies &#x60;refresh_token&#x60; (HttpOnly) et &#x60;csrf_token&#x60; sont posés via &#x60;Set-Cookie&#x60;.  </td><td>  * Set-Cookie - Deux cookies sont émis : &#x60;refresh_token&#x3D;&lt;opaque&gt;; HttpOnly; Secure; SameSite&#x3D;None; Path&#x3D;/api/v1/auth; Max-Age&#x3D;2592000&#x60; et &#x60;csrf_token&#x3D;&lt;value&gt;; Secure; SameSite&#x3D;None; Path&#x3D;/api/v1/auth; Max-Age&#x3D;2592000&#x60;.  <br>  </td></tr>
        <tr><td> 401 </td><td> Token JWT manquant ou invalide </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call authLoginPostCall(@javax.annotation.Nonnull LoginRequest loginRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = loginRequest;

        // create path and map variables
        String localVarPath = "/auth/login";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call authLoginPostValidateBeforeCall(@javax.annotation.Nonnull LoginRequest loginRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'loginRequest' is set
        if (loginRequest == null) {
            throw new ApiException("Missing the required parameter 'loginRequest' when calling authLoginPost(Async)");
        }

        return authLoginPostCall(loginRequest, _callback);

    }

    /**
     * Connexion — obtenir un JWT et poser les cookies refresh/csrf
     * 
     * @param loginRequest  (required)
     * @return LoginResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Access JWT retourné dans le corps. Les cookies &#x60;refresh_token&#x60; (HttpOnly) et &#x60;csrf_token&#x60; sont posés via &#x60;Set-Cookie&#x60;.  </td><td>  * Set-Cookie - Deux cookies sont émis : &#x60;refresh_token&#x3D;&lt;opaque&gt;; HttpOnly; Secure; SameSite&#x3D;None; Path&#x3D;/api/v1/auth; Max-Age&#x3D;2592000&#x60; et &#x60;csrf_token&#x3D;&lt;value&gt;; Secure; SameSite&#x3D;None; Path&#x3D;/api/v1/auth; Max-Age&#x3D;2592000&#x60;.  <br>  </td></tr>
        <tr><td> 401 </td><td> Token JWT manquant ou invalide </td><td>  -  </td></tr>
     </table>
     */
    public LoginResponse authLoginPost(@javax.annotation.Nonnull LoginRequest loginRequest) throws ApiException {
        ApiResponse<LoginResponse> localVarResp = authLoginPostWithHttpInfo(loginRequest);
        return localVarResp.getData();
    }

    /**
     * Connexion — obtenir un JWT et poser les cookies refresh/csrf
     * 
     * @param loginRequest  (required)
     * @return ApiResponse&lt;LoginResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Access JWT retourné dans le corps. Les cookies &#x60;refresh_token&#x60; (HttpOnly) et &#x60;csrf_token&#x60; sont posés via &#x60;Set-Cookie&#x60;.  </td><td>  * Set-Cookie - Deux cookies sont émis : &#x60;refresh_token&#x3D;&lt;opaque&gt;; HttpOnly; Secure; SameSite&#x3D;None; Path&#x3D;/api/v1/auth; Max-Age&#x3D;2592000&#x60; et &#x60;csrf_token&#x3D;&lt;value&gt;; Secure; SameSite&#x3D;None; Path&#x3D;/api/v1/auth; Max-Age&#x3D;2592000&#x60;.  <br>  </td></tr>
        <tr><td> 401 </td><td> Token JWT manquant ou invalide </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<LoginResponse> authLoginPostWithHttpInfo(@javax.annotation.Nonnull LoginRequest loginRequest) throws ApiException {
        okhttp3.Call localVarCall = authLoginPostValidateBeforeCall(loginRequest, null);
        Type localVarReturnType = new TypeToken<LoginResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Connexion — obtenir un JWT et poser les cookies refresh/csrf (asynchronously)
     * 
     * @param loginRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Access JWT retourné dans le corps. Les cookies &#x60;refresh_token&#x60; (HttpOnly) et &#x60;csrf_token&#x60; sont posés via &#x60;Set-Cookie&#x60;.  </td><td>  * Set-Cookie - Deux cookies sont émis : &#x60;refresh_token&#x3D;&lt;opaque&gt;; HttpOnly; Secure; SameSite&#x3D;None; Path&#x3D;/api/v1/auth; Max-Age&#x3D;2592000&#x60; et &#x60;csrf_token&#x3D;&lt;value&gt;; Secure; SameSite&#x3D;None; Path&#x3D;/api/v1/auth; Max-Age&#x3D;2592000&#x60;.  <br>  </td></tr>
        <tr><td> 401 </td><td> Token JWT manquant ou invalide </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call authLoginPostAsync(@javax.annotation.Nonnull LoginRequest loginRequest, final ApiCallback<LoginResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = authLoginPostValidateBeforeCall(loginRequest, _callback);
        Type localVarReturnType = new TypeToken<LoginResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for authLogoutPost
     * @param xCSRFToken  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Déconnexion réussie </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Token JWT manquant ou invalide </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> CSRF token manquant ou invalide. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call authLogoutPostCall(@javax.annotation.Nonnull String xCSRFToken, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/auth/logout";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xCSRFToken != null) {
            localVarHeaderParams.put("X-CSRF-Token", localVarApiClient.parameterToString(xCSRFToken));
        }


        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call authLogoutPostValidateBeforeCall(@javax.annotation.Nonnull String xCSRFToken, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'xCSRFToken' is set
        if (xCSRFToken == null) {
            throw new ApiException("Missing the required parameter 'xCSRFToken' when calling authLogoutPost(Async)");
        }

        return authLogoutPostCall(xCSRFToken, _callback);

    }

    /**
     * Révocation du refresh token courant et nettoyage des cookies
     * Révoque le refresh token courant côté serveur et efface les cookies &#x60;refresh_token&#x60; et &#x60;csrf_token&#x60; (Max-Age&#x3D;0). Le header &#x60;X-CSRF-Token&#x60; est requis. 
     * @param xCSRFToken  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Déconnexion réussie </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Token JWT manquant ou invalide </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> CSRF token manquant ou invalide. </td><td>  -  </td></tr>
     </table>
     */
    public void authLogoutPost(@javax.annotation.Nonnull String xCSRFToken) throws ApiException {
        authLogoutPostWithHttpInfo(xCSRFToken);
    }

    /**
     * Révocation du refresh token courant et nettoyage des cookies
     * Révoque le refresh token courant côté serveur et efface les cookies &#x60;refresh_token&#x60; et &#x60;csrf_token&#x60; (Max-Age&#x3D;0). Le header &#x60;X-CSRF-Token&#x60; est requis. 
     * @param xCSRFToken  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Déconnexion réussie </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Token JWT manquant ou invalide </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> CSRF token manquant ou invalide. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> authLogoutPostWithHttpInfo(@javax.annotation.Nonnull String xCSRFToken) throws ApiException {
        okhttp3.Call localVarCall = authLogoutPostValidateBeforeCall(xCSRFToken, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Révocation du refresh token courant et nettoyage des cookies (asynchronously)
     * Révoque le refresh token courant côté serveur et efface les cookies &#x60;refresh_token&#x60; et &#x60;csrf_token&#x60; (Max-Age&#x3D;0). Le header &#x60;X-CSRF-Token&#x60; est requis. 
     * @param xCSRFToken  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Déconnexion réussie </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Token JWT manquant ou invalide </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> CSRF token manquant ou invalide. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call authLogoutPostAsync(@javax.annotation.Nonnull String xCSRFToken, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = authLogoutPostValidateBeforeCall(xCSRFToken, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for authRefreshPost
     * @param xCSRFToken Doit être égal au cookie &#x60;csrf_token&#x60;. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Nouvel access JWT + cookies refresh/csrf rotés. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Token JWT manquant ou invalide </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> CSRF token manquant ou invalide. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call authRefreshPostCall(@javax.annotation.Nonnull String xCSRFToken, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/auth/refresh";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xCSRFToken != null) {
            localVarHeaderParams.put("X-CSRF-Token", localVarApiClient.parameterToString(xCSRFToken));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call authRefreshPostValidateBeforeCall(@javax.annotation.Nonnull String xCSRFToken, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'xCSRFToken' is set
        if (xCSRFToken == null) {
            throw new ApiException("Missing the required parameter 'xCSRFToken' when calling authRefreshPost(Async)");
        }

        return authRefreshPostCall(xCSRFToken, _callback);

    }

    /**
     * Rotation du refresh token et émission d&#39;un nouvel access JWT
     * Lit le cookie &#x60;refresh_token&#x60; (envoyé automatiquement par le navigateur avec &#x60;credentials: &#39;include&#39;&#x60;). Vérifie la signature CSRF via header &#x60;X-CSRF-Token&#x60; (doit valoir la même chose que le cookie &#x60;csrf_token&#x60;). Révoque le refresh précédent et en émet un nouveau (rotation). Si un refresh déjà révoqué est présenté → 401 et toute la famille de tokens est invalidée (reuse detection). 
     * @param xCSRFToken Doit être égal au cookie &#x60;csrf_token&#x60;. (required)
     * @return LoginResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Nouvel access JWT + cookies refresh/csrf rotés. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Token JWT manquant ou invalide </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> CSRF token manquant ou invalide. </td><td>  -  </td></tr>
     </table>
     */
    public LoginResponse authRefreshPost(@javax.annotation.Nonnull String xCSRFToken) throws ApiException {
        ApiResponse<LoginResponse> localVarResp = authRefreshPostWithHttpInfo(xCSRFToken);
        return localVarResp.getData();
    }

    /**
     * Rotation du refresh token et émission d&#39;un nouvel access JWT
     * Lit le cookie &#x60;refresh_token&#x60; (envoyé automatiquement par le navigateur avec &#x60;credentials: &#39;include&#39;&#x60;). Vérifie la signature CSRF via header &#x60;X-CSRF-Token&#x60; (doit valoir la même chose que le cookie &#x60;csrf_token&#x60;). Révoque le refresh précédent et en émet un nouveau (rotation). Si un refresh déjà révoqué est présenté → 401 et toute la famille de tokens est invalidée (reuse detection). 
     * @param xCSRFToken Doit être égal au cookie &#x60;csrf_token&#x60;. (required)
     * @return ApiResponse&lt;LoginResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Nouvel access JWT + cookies refresh/csrf rotés. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Token JWT manquant ou invalide </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> CSRF token manquant ou invalide. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<LoginResponse> authRefreshPostWithHttpInfo(@javax.annotation.Nonnull String xCSRFToken) throws ApiException {
        okhttp3.Call localVarCall = authRefreshPostValidateBeforeCall(xCSRFToken, null);
        Type localVarReturnType = new TypeToken<LoginResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Rotation du refresh token et émission d&#39;un nouvel access JWT (asynchronously)
     * Lit le cookie &#x60;refresh_token&#x60; (envoyé automatiquement par le navigateur avec &#x60;credentials: &#39;include&#39;&#x60;). Vérifie la signature CSRF via header &#x60;X-CSRF-Token&#x60; (doit valoir la même chose que le cookie &#x60;csrf_token&#x60;). Révoque le refresh précédent et en émet un nouveau (rotation). Si un refresh déjà révoqué est présenté → 401 et toute la famille de tokens est invalidée (reuse detection). 
     * @param xCSRFToken Doit être égal au cookie &#x60;csrf_token&#x60;. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Nouvel access JWT + cookies refresh/csrf rotés. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Token JWT manquant ou invalide </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> CSRF token manquant ou invalide. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call authRefreshPostAsync(@javax.annotation.Nonnull String xCSRFToken, final ApiCallback<LoginResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = authRefreshPostValidateBeforeCall(xCSRFToken, _callback);
        Type localVarReturnType = new TypeToken<LoginResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for authRegisterPost
     * @param registerRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Utilisateur créé </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Données invalides </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call authRegisterPostCall(@javax.annotation.Nonnull RegisterRequest registerRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = registerRequest;

        // create path and map variables
        String localVarPath = "/auth/register";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call authRegisterPostValidateBeforeCall(@javax.annotation.Nonnull RegisterRequest registerRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'registerRequest' is set
        if (registerRequest == null) {
            throw new ApiException("Missing the required parameter 'registerRequest' when calling authRegisterPost(Async)");
        }

        return authRegisterPostCall(registerRequest, _callback);

    }

    /**
     * Inscription d&#39;un nouvel utilisateur
     * 
     * @param registerRequest  (required)
     * @return User
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Utilisateur créé </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Données invalides </td><td>  -  </td></tr>
     </table>
     */
    public User authRegisterPost(@javax.annotation.Nonnull RegisterRequest registerRequest) throws ApiException {
        ApiResponse<User> localVarResp = authRegisterPostWithHttpInfo(registerRequest);
        return localVarResp.getData();
    }

    /**
     * Inscription d&#39;un nouvel utilisateur
     * 
     * @param registerRequest  (required)
     * @return ApiResponse&lt;User&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Utilisateur créé </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Données invalides </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<User> authRegisterPostWithHttpInfo(@javax.annotation.Nonnull RegisterRequest registerRequest) throws ApiException {
        okhttp3.Call localVarCall = authRegisterPostValidateBeforeCall(registerRequest, null);
        Type localVarReturnType = new TypeToken<User>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Inscription d&#39;un nouvel utilisateur (asynchronously)
     * 
     * @param registerRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Utilisateur créé </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Données invalides </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call authRegisterPostAsync(@javax.annotation.Nonnull RegisterRequest registerRequest, final ApiCallback<User> _callback) throws ApiException {

        okhttp3.Call localVarCall = authRegisterPostValidateBeforeCall(registerRequest, _callback);
        Type localVarReturnType = new TypeToken<User>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
