/*
 * La Caverne Malgache API
 * Documentation OpenAPI de La Caverne Malagasy. Couvre l'ensemble des ressources : utilisateurs, catalogue, commandes, paiements, livraisons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.DeliverCost;
import org.openapitools.client.model.DeliverCostInput;
import org.openapitools.client.model.Error;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DeliveryCostsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public DeliveryCostsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public DeliveryCostsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for deliveryCostsGet
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deliveryCostsGetCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/delivery-costs";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deliveryCostsGetValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return deliveryCostsGetCall(_callback);

    }

    /**
     * Liste des coûts de livraison
     * 
     * @return List&lt;DeliverCost&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public List<DeliverCost> deliveryCostsGet() throws ApiException {
        ApiResponse<List<DeliverCost>> localVarResp = deliveryCostsGetWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Liste des coûts de livraison
     * 
     * @return ApiResponse&lt;List&lt;DeliverCost&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<DeliverCost>> deliveryCostsGetWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = deliveryCostsGetValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<List<DeliverCost>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Liste des coûts de livraison (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deliveryCostsGetAsync(final ApiCallback<List<DeliverCost>> _callback) throws ApiException {

        okhttp3.Call localVarCall = deliveryCostsGetValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<List<DeliverCost>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deliveryCostsIdDelete
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Supprimé </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Token JWT manquant ou invalide </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (rôle insuffisant) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource introuvable </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deliveryCostsIdDeleteCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/delivery-costs/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deliveryCostsIdDeleteValidateBeforeCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling deliveryCostsIdDelete(Async)");
        }

        return deliveryCostsIdDeleteCall(id, _callback);

    }

    /**
     * Supprimer un coût de livraison (admin)
     * 
     * @param id  (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Supprimé </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Token JWT manquant ou invalide </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (rôle insuffisant) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource introuvable </td><td>  -  </td></tr>
     </table>
     */
    public void deliveryCostsIdDelete(@javax.annotation.Nonnull Integer id) throws ApiException {
        deliveryCostsIdDeleteWithHttpInfo(id);
    }

    /**
     * Supprimer un coût de livraison (admin)
     * 
     * @param id  (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Supprimé </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Token JWT manquant ou invalide </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (rôle insuffisant) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource introuvable </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> deliveryCostsIdDeleteWithHttpInfo(@javax.annotation.Nonnull Integer id) throws ApiException {
        okhttp3.Call localVarCall = deliveryCostsIdDeleteValidateBeforeCall(id, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Supprimer un coût de livraison (admin) (asynchronously)
     * 
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> Supprimé </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Token JWT manquant ou invalide </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (rôle insuffisant) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource introuvable </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deliveryCostsIdDeleteAsync(@javax.annotation.Nonnull Integer id, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = deliveryCostsIdDeleteValidateBeforeCall(id, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for deliveryCostsIdGet
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource introuvable </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deliveryCostsIdGetCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/delivery-costs/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deliveryCostsIdGetValidateBeforeCall(@javax.annotation.Nonnull Integer id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling deliveryCostsIdGet(Async)");
        }

        return deliveryCostsIdGetCall(id, _callback);

    }

    /**
     * Détail d&#39;un coût de livraison
     * 
     * @param id  (required)
     * @return DeliverCost
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource introuvable </td><td>  -  </td></tr>
     </table>
     */
    public DeliverCost deliveryCostsIdGet(@javax.annotation.Nonnull Integer id) throws ApiException {
        ApiResponse<DeliverCost> localVarResp = deliveryCostsIdGetWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Détail d&#39;un coût de livraison
     * 
     * @param id  (required)
     * @return ApiResponse&lt;DeliverCost&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource introuvable </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DeliverCost> deliveryCostsIdGetWithHttpInfo(@javax.annotation.Nonnull Integer id) throws ApiException {
        okhttp3.Call localVarCall = deliveryCostsIdGetValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<DeliverCost>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Détail d&#39;un coût de livraison (asynchronously)
     * 
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource introuvable </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deliveryCostsIdGetAsync(@javax.annotation.Nonnull Integer id, final ApiCallback<DeliverCost> _callback) throws ApiException {

        okhttp3.Call localVarCall = deliveryCostsIdGetValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<DeliverCost>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deliveryCostsIdPut
     * @param id  (required)
     * @param deliverCostInput  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Coût de livraison mis à jour </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Token JWT manquant ou invalide </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (rôle insuffisant) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource introuvable </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Données invalides </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deliveryCostsIdPutCall(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull DeliverCostInput deliverCostInput, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = deliverCostInput;

        // create path and map variables
        String localVarPath = "/delivery-costs/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deliveryCostsIdPutValidateBeforeCall(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull DeliverCostInput deliverCostInput, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling deliveryCostsIdPut(Async)");
        }

        // verify the required parameter 'deliverCostInput' is set
        if (deliverCostInput == null) {
            throw new ApiException("Missing the required parameter 'deliverCostInput' when calling deliveryCostsIdPut(Async)");
        }

        return deliveryCostsIdPutCall(id, deliverCostInput, _callback);

    }

    /**
     * Mettre à jour un coût de livraison (admin)
     * 
     * @param id  (required)
     * @param deliverCostInput  (required)
     * @return DeliverCost
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Coût de livraison mis à jour </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Token JWT manquant ou invalide </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (rôle insuffisant) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource introuvable </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Données invalides </td><td>  -  </td></tr>
     </table>
     */
    public DeliverCost deliveryCostsIdPut(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull DeliverCostInput deliverCostInput) throws ApiException {
        ApiResponse<DeliverCost> localVarResp = deliveryCostsIdPutWithHttpInfo(id, deliverCostInput);
        return localVarResp.getData();
    }

    /**
     * Mettre à jour un coût de livraison (admin)
     * 
     * @param id  (required)
     * @param deliverCostInput  (required)
     * @return ApiResponse&lt;DeliverCost&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Coût de livraison mis à jour </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Token JWT manquant ou invalide </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (rôle insuffisant) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource introuvable </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Données invalides </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DeliverCost> deliveryCostsIdPutWithHttpInfo(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull DeliverCostInput deliverCostInput) throws ApiException {
        okhttp3.Call localVarCall = deliveryCostsIdPutValidateBeforeCall(id, deliverCostInput, null);
        Type localVarReturnType = new TypeToken<DeliverCost>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Mettre à jour un coût de livraison (admin) (asynchronously)
     * 
     * @param id  (required)
     * @param deliverCostInput  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Coût de livraison mis à jour </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Token JWT manquant ou invalide </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (rôle insuffisant) </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Ressource introuvable </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Données invalides </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deliveryCostsIdPutAsync(@javax.annotation.Nonnull Integer id, @javax.annotation.Nonnull DeliverCostInput deliverCostInput, final ApiCallback<DeliverCost> _callback) throws ApiException {

        okhttp3.Call localVarCall = deliveryCostsIdPutValidateBeforeCall(id, deliverCostInput, _callback);
        Type localVarReturnType = new TypeToken<DeliverCost>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for deliveryCostsPost
     * @param deliverCostInput  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Coût de livraison créé </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Token JWT manquant ou invalide </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (rôle insuffisant) </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Données invalides </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deliveryCostsPostCall(@javax.annotation.Nonnull DeliverCostInput deliverCostInput, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = deliverCostInput;

        // create path and map variables
        String localVarPath = "/delivery-costs";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call deliveryCostsPostValidateBeforeCall(@javax.annotation.Nonnull DeliverCostInput deliverCostInput, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'deliverCostInput' is set
        if (deliverCostInput == null) {
            throw new ApiException("Missing the required parameter 'deliverCostInput' when calling deliveryCostsPost(Async)");
        }

        return deliveryCostsPostCall(deliverCostInput, _callback);

    }

    /**
     * Créer un coût de livraison (admin)
     * 
     * @param deliverCostInput  (required)
     * @return DeliverCost
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Coût de livraison créé </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Token JWT manquant ou invalide </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (rôle insuffisant) </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Données invalides </td><td>  -  </td></tr>
     </table>
     */
    public DeliverCost deliveryCostsPost(@javax.annotation.Nonnull DeliverCostInput deliverCostInput) throws ApiException {
        ApiResponse<DeliverCost> localVarResp = deliveryCostsPostWithHttpInfo(deliverCostInput);
        return localVarResp.getData();
    }

    /**
     * Créer un coût de livraison (admin)
     * 
     * @param deliverCostInput  (required)
     * @return ApiResponse&lt;DeliverCost&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Coût de livraison créé </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Token JWT manquant ou invalide </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (rôle insuffisant) </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Données invalides </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DeliverCost> deliveryCostsPostWithHttpInfo(@javax.annotation.Nonnull DeliverCostInput deliverCostInput) throws ApiException {
        okhttp3.Call localVarCall = deliveryCostsPostValidateBeforeCall(deliverCostInput, null);
        Type localVarReturnType = new TypeToken<DeliverCost>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Créer un coût de livraison (admin) (asynchronously)
     * 
     * @param deliverCostInput  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Coût de livraison créé </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Token JWT manquant ou invalide </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Accès refusé (rôle insuffisant) </td><td>  -  </td></tr>
        <tr><td> 422 </td><td> Données invalides </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call deliveryCostsPostAsync(@javax.annotation.Nonnull DeliverCostInput deliverCostInput, final ApiCallback<DeliverCost> _callback) throws ApiException {

        okhttp3.Call localVarCall = deliveryCostsPostValidateBeforeCall(deliverCostInput, _callback);
        Type localVarReturnType = new TypeToken<DeliverCost>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
