/*
 * La Caverne Malgache API
 * Documentation OpenAPI de La Caverne Malagasy. Couvre l'ensemble des ressources : utilisateurs, catalogue, commandes, paiements, livraisons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentMethodInput
 */
public class PaymentMethodInputTest {
    private final PaymentMethodInput model = new PaymentMethodInput();

    /**
     * Model tests for PaymentMethodInput
     */
    @Test
    public void testPaymentMethodInput() {
        // TODO: test PaymentMethodInput
    }

    /**
     * Test the property 'providerCode'
     */
    @Test
    public void providerCodeTest() {
        // TODO: test providerCode
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'isActive'
     */
    @Test
    public void isActiveTest() {
        // TODO: test isActive
    }

    /**
     * Test the property 'requiresManualCheck'
     */
    @Test
    public void requiresManualCheckTest() {
        // TODO: test requiresManualCheck
    }

    /**
     * Test the property 'integrationType'
     */
    @Test
    public void integrationTypeTest() {
        // TODO: test integrationType
    }

}
