/*
 * La Caverne Malgache API
 * Documentation OpenAPI de La Caverne Malagasy. Couvre l'ensemble des ressources : utilisateurs, catalogue, commandes, paiements, livraisons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TechnicalSpecsInput
 */
public class TechnicalSpecsInputTest {
    private final TechnicalSpecsInput model = new TechnicalSpecsInput();

    /**
     * Model tests for TechnicalSpecsInput
     */
    @Test
    public void testTechnicalSpecsInput() {
        // TODO: test TechnicalSpecsInput
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'region'
     */
    @Test
    public void regionTest() {
        // TODO: test region
    }

    /**
     * Test the property 'climate'
     */
    @Test
    public void climateTest() {
        // TODO: test climate
    }

    /**
     * Test the property 'provider'
     */
    @Test
    public void providerTest() {
        // TODO: test provider
    }

}
