/*
 * La Caverne Malgache API
 * Documentation OpenAPI de La Caverne Malagasy. Couvre l'ensemble des ressources : utilisateurs, catalogue, commandes, paiements, livraisons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.LoginRequest;
import org.openapitools.client.model.LoginResponse;
import org.openapitools.client.model.RegisterRequest;
import org.openapitools.client.model.User;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthApi
 */
@Disabled
public class AuthApiTest {

    private final AuthApi api = new AuthApi();

    /**
     * Connexion — obtenir un JWT
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void authLoginPostTest() throws ApiException {
        LoginRequest loginRequest = null;
        LoginResponse response = api.authLoginPost(loginRequest);
        // TODO: test validations
    }

    /**
     * Invalidation du token JWT courant
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void authLogoutPostTest() throws ApiException {
        api.authLogoutPost();
        // TODO: test validations
    }

    /**
     * Inscription d&#39;un nouvel utilisateur
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void authRegisterPostTest() throws ApiException {
        RegisterRequest registerRequest = null;
        User response = api.authRegisterPost(registerRequest);
        // TODO: test validations
    }

}
