/*
 * La Caverne Malgache API
 * Documentation OpenAPI de La Caverne Malagasy. Couvre l'ensemble des ressources : utilisateurs, catalogue, commandes, paiements, livraisons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.LoginRequest;
import org.openapitools.client.model.LoginResponse;
import org.openapitools.client.model.RegisterRequest;
import org.openapitools.client.model.User;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthApi
 */
@Disabled
public class AuthApiTest {

    private final AuthApi api = new AuthApi();

    /**
     * Connexion — obtenir un JWT et poser les cookies refresh/csrf
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void authLoginPostTest() throws ApiException {
        LoginRequest loginRequest = null;
        LoginResponse response = api.authLoginPost(loginRequest);
        // TODO: test validations
    }

    /**
     * Révocation du refresh token courant et nettoyage des cookies
     *
     * Révoque le refresh token courant côté serveur et efface les cookies &#x60;refresh_token&#x60; et &#x60;csrf_token&#x60; (Max-Age&#x3D;0). Le header &#x60;X-CSRF-Token&#x60; est requis. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void authLogoutPostTest() throws ApiException {
        String xCSRFToken = null;
        api.authLogoutPost(xCSRFToken);
        // TODO: test validations
    }

    /**
     * Rotation du refresh token et émission d&#39;un nouvel access JWT
     *
     * Lit le cookie &#x60;refresh_token&#x60; (envoyé automatiquement par le navigateur avec &#x60;credentials: &#39;include&#39;&#x60;). Vérifie la signature CSRF via header &#x60;X-CSRF-Token&#x60; (doit valoir la même chose que le cookie &#x60;csrf_token&#x60;). Révoque le refresh précédent et en émet un nouveau (rotation). Si un refresh déjà révoqué est présenté → 401 et toute la famille de tokens est invalidée (reuse detection). 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void authRefreshPostTest() throws ApiException {
        String xCSRFToken = null;
        LoginResponse response = api.authRefreshPost(xCSRFToken);
        // TODO: test validations
    }

    /**
     * Inscription d&#39;un nouvel utilisateur
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void authRegisterPostTest() throws ApiException {
        RegisterRequest registerRequest = null;
        User response = api.authRegisterPost(registerRequest);
        // TODO: test validations
    }

}
