/*
 * La Caverne Malgache API
 * Documentation OpenAPI de La Caverne Malagasy. Couvre l'ensemble des ressources : utilisateurs, catalogue, commandes, paiements, livraisons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Currency;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CurrenciesApi
 */
@Disabled
public class CurrenciesApiTest {

    private final CurrenciesApi api = new CurrenciesApi();

    /**
     * Supprimer une devise (admin)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void currenciesCodeIsoDeleteTest() throws ApiException {
        String codeIso = null;
        api.currenciesCodeIsoDelete(codeIso);
        // TODO: test validations
    }

    /**
     * Modifier une devise (admin)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void currenciesCodeIsoPutTest() throws ApiException {
        String codeIso = null;
        Currency currency = null;
        Currency response = api.currenciesCodeIsoPut(codeIso, currency);
        // TODO: test validations
    }

    /**
     * Liste des devises supportées
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void currenciesGetTest() throws ApiException {
        List<Currency> response = api.currenciesGet();
        // TODO: test validations
    }

    /**
     * Ajouter une devise (admin)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void currenciesPostTest() throws ApiException {
        Currency currency = null;
        Currency response = api.currenciesPost(currency);
        // TODO: test validations
    }

}
