/*
 * La Caverne Malgache API
 * Documentation OpenAPI de La Caverne Malagasy. Couvre l'ensemble des ressources : utilisateurs, catalogue, commandes, paiements, livraisons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.Order;
import org.openapitools.client.model.OrderInput;
import org.openapitools.client.model.OrderStatusUpdate;
import org.openapitools.client.model.OrdersGet200Response;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrdersApi
 */
@Disabled
public class OrdersApiTest {

    private final OrdersApi api = new OrdersApi();

    /**
     * Toutes les commandes (admin)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ordersAllGetTest() throws ApiException {
        Integer page = null;
        Integer perPage = null;
        String status = null;
        UUID userId = null;
        OrdersGet200Response response = api.ordersAllGet(page, perPage, status, userId);
        // TODO: test validations
    }

    /**
     * Mes commandes (utilisateur connecté)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ordersGetTest() throws ApiException {
        Integer page = null;
        String status = null;
        OrdersGet200Response response = api.ordersGet(page, status);
        // TODO: test validations
    }

    /**
     * Annuler une commande (owner ou admin)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ordersIdCancelPostTest() throws ApiException {
        UUID id = null;
        Order response = api.ordersIdCancelPost(id);
        // TODO: test validations
    }

    /**
     * Détail d&#39;une commande
     *
     * Les commandes invitées peuvent être consultées sans authentification. Les commandes liées à un utilisateur nécessitent que l&#39;acteur soit le propriétaire ou un admin. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ordersIdGetTest() throws ApiException {
        UUID id = null;
        Order response = api.ordersIdGet(id);
        // TODO: test validations
    }

    /**
     * Changer le statut d&#39;une commande (admin)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ordersIdStatusPutTest() throws ApiException {
        UUID id = null;
        OrderStatusUpdate orderStatusUpdate = null;
        Order response = api.ordersIdStatusPut(id, orderStatusUpdate);
        // TODO: test validations
    }

    /**
     * Passer une commande
     *
     * Crée une commande et décrémente le stock de chaque produit demandé. Le stock est verrouillé en écriture (SELECT FOR UPDATE) pendant la transaction, de sorte que deux commandes concurrentes sur le même produit sont sérialisées : la seconde relit le stock à jour et reçoit &#x60;422&#x60; si la quantité est insuffisante. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ordersPostTest() throws ApiException {
        OrderInput orderInput = null;
        Order response = api.ordersPost(orderInput);
        // TODO: test validations
    }

}
