/*
 * La Caverne Malgache API
 * Documentation OpenAPI de La Caverne Malagasy. Couvre l'ensemble des ressources : utilisateurs, catalogue, commandes, paiements, livraisons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.Payment;
import org.openapitools.client.model.PaymentInput;
import org.openapitools.client.model.PaymentMethod;
import org.openapitools.client.model.StripeEvent;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaymentsApi
 */
@Disabled
public class PaymentsApiTest {

    private final PaymentsApi api = new PaymentsApi();

    /**
     * Paiements associés à une commande
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ordersIdPaymentsGetTest() throws ApiException {
        UUID id = null;
        List<Payment> response = api.ordersIdPaymentsGet(id);
        // TODO: test validations
    }

    /**
     * Initier un paiement
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ordersIdPaymentsPostTest() throws ApiException {
        UUID id = null;
        PaymentInput paymentInput = null;
        Payment response = api.ordersIdPaymentsPost(id, paymentInput);
        // TODO: test validations
    }

    /**
     * Liste des moyens de paiement disponibles
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void paymentMethodsGetTest() throws ApiException {
        List<PaymentMethod> response = api.paymentMethodsGet();
        // TODO: test validations
    }

    /**
     * Webhook Stripe Checkout
     *
     * Endpoint invoqué par Stripe. Le corps est un objet Event Stripe brut (https://stripe.com/docs/api/events/object). Les requêtes doivent porter l&#39;en-tête &#x60;Stripe-Signature&#x60; ; il est vérifié contre &#x60;stripe.webhook-secret&#x60;. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void paymentsWebhooksStripePostTest() throws ApiException {
        String stripeSignature = null;
        StripeEvent stripeEvent = null;
        api.paymentsWebhooksStripePost(stripeSignature, stripeEvent);
        // TODO: test validations
    }

}
