/*
 * La Caverne Malgache API
 * Documentation OpenAPI de La Caverne Malagasy. Couvre l'ensemble des ressources : utilisateurs, catalogue, commandes, paiements, livraisons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.Payment;
import org.openapitools.client.model.PaymentInput;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaymentsApi
 */
@Disabled
public class PaymentsApiTest {

    private final PaymentsApi api = new PaymentsApi();

    /**
     * Paiements associés à une commande
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ordersIdPaymentsGetTest() throws ApiException {
        Integer id = null;
        List<Payment> response = api.ordersIdPaymentsGet(id);
        // TODO: test validations
    }

    /**
     * Initier un paiement
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void ordersIdPaymentsPostTest() throws ApiException {
        Integer id = null;
        PaymentInput paymentInput = null;
        Payment response = api.ordersIdPaymentsPost(id, paymentInput);
        // TODO: test validations
    }

}
