/*
 * La Caverne Malgache API
 * Documentation OpenAPI de La Caverne Malagasy. Couvre l'ensemble des ressources : utilisateurs, catalogue, commandes, paiements, livraisons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.Product;
import org.openapitools.client.model.ProductInput;
import org.openapitools.client.model.ProductsGet200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProductsApi
 */
@Disabled
public class ProductsApiTest {

    private final ProductsApi api = new ProductsApi();

    /**
     * Catalogue produits
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void productsGetTest() throws ApiException {
        Integer page = null;
        Integer perPage = null;
        Integer categoryId = null;
        Boolean isActive = null;
        String search = null;
        String currency = null;
        ProductsGet200Response response = api.productsGet(page, perPage, categoryId, isActive, search, currency);
        // TODO: test validations
    }

    /**
     * Supprimer un produit (admin)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void productsIdDeleteTest() throws ApiException {
        Integer id = null;
        api.productsIdDelete(id);
        // TODO: test validations
    }

    /**
     * Détail d&#39;un produit
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void productsIdGetTest() throws ApiException {
        Integer id = null;
        Product response = api.productsIdGet(id);
        // TODO: test validations
    }

    /**
     * Modifier un produit (admin)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void productsIdPutTest() throws ApiException {
        Integer id = null;
        ProductInput productInput = null;
        Product response = api.productsIdPut(id, productInput);
        // TODO: test validations
    }

    /**
     * Créer un produit (admin)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void productsPostTest() throws ApiException {
        ProductInput productInput = null;
        Product response = api.productsPost(productInput);
        // TODO: test validations
    }

}
