/*
 * La Caverne Malgache API
 * Documentation OpenAPI de La Caverne Malagasy. Couvre l'ensemble des ressources : utilisateurs, catalogue, commandes, paiements, livraisons. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.Price;
import org.openapitools.client.model.PriceInput;
import org.openapitools.client.model.Product;
import org.openapitools.client.model.ProductImage;
import org.openapitools.client.model.ProductImageInput;
import org.openapitools.client.model.ProductInput;
import org.openapitools.client.model.ProductsGet200Response;
import org.openapitools.client.model.ProductsIdReviewsGet200Response;
import org.openapitools.client.model.ProductsIdStockHistoryGet200Response;
import org.openapitools.client.model.Review;
import org.openapitools.client.model.ReviewInput;
import org.openapitools.client.model.StockEntry;
import org.openapitools.client.model.StockInput;
import org.openapitools.client.model.StockSummary;
import org.openapitools.client.model.TechnicalSpecs;
import org.openapitools.client.model.TechnicalSpecsInput;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProductsApi
 */
@Disabled
public class ProductsApiTest {

    private final ProductsApi api = new ProductsApi();

    /**
     * Catalogue produits
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void productsGetTest() throws ApiException {
        Integer page = null;
        Integer perPage = null;
        Integer categoryId = null;
        Boolean isActive = null;
        String search = null;
        String currency = null;
        ProductsGet200Response response = api.productsGet(page, perPage, categoryId, isActive, search, currency);
        // TODO: test validations
    }

    /**
     * Supprimer un produit (admin)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void productsIdDeleteTest() throws ApiException {
        Integer id = null;
        api.productsIdDelete(id);
        // TODO: test validations
    }

    /**
     * Détail d&#39;un produit
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void productsIdGetTest() throws ApiException {
        Integer id = null;
        Product response = api.productsIdGet(id);
        // TODO: test validations
    }

    /**
     * Images d&#39;un produit
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void productsIdImagesGetTest() throws ApiException {
        Integer id = null;
        List<ProductImage> response = api.productsIdImagesGet(id);
        // TODO: test validations
    }

    /**
     * Supprimer une image
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void productsIdImagesImageIdDeleteTest() throws ApiException {
        Integer id = null;
        Integer imageId = null;
        api.productsIdImagesImageIdDelete(id, imageId);
        // TODO: test validations
    }

    /**
     * Modifier une image (définir main, etc.)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void productsIdImagesImageIdPutTest() throws ApiException {
        Integer id = null;
        Integer imageId = null;
        ProductImageInput productImageInput = null;
        ProductImage response = api.productsIdImagesImageIdPut(id, imageId, productImageInput);
        // TODO: test validations
    }

    /**
     * Ajouter une image (admin)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void productsIdImagesPostTest() throws ApiException {
        Integer id = null;
        ProductImageInput productImageInput = null;
        ProductImage response = api.productsIdImagesPost(id, productImageInput);
        // TODO: test validations
    }

    /**
     * Historique des prix d&#39;un produit
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void productsIdPricesGetTest() throws ApiException {
        Integer id = null;
        List<Price> response = api.productsIdPricesGet(id);
        // TODO: test validations
    }

    /**
     * Ajouter un prix (admin)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void productsIdPricesPostTest() throws ApiException {
        Integer id = null;
        PriceInput priceInput = null;
        Price response = api.productsIdPricesPost(id, priceInput);
        // TODO: test validations
    }

    /**
     * Modifier un produit (admin)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void productsIdPutTest() throws ApiException {
        Integer id = null;
        ProductInput productInput = null;
        Product response = api.productsIdPut(id, productInput);
        // TODO: test validations
    }

    /**
     * Avis clients d&#39;un produit
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void productsIdReviewsGetTest() throws ApiException {
        Integer id = null;
        Integer page = null;
        ProductsIdReviewsGet200Response response = api.productsIdReviewsGet(id, page);
        // TODO: test validations
    }

    /**
     * Déposer un avis (utilisateur connecté)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void productsIdReviewsPostTest() throws ApiException {
        Integer id = null;
        ReviewInput reviewInput = null;
        Review response = api.productsIdReviewsPost(id, reviewInput);
        // TODO: test validations
    }

    /**
     * Stock disponible d&#39;un produit
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void productsIdStockGetTest() throws ApiException {
        Integer id = null;
        StockSummary response = api.productsIdStockGet(id);
        // TODO: test validations
    }

    /**
     * Historique des mouvements de stock
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void productsIdStockHistoryGetTest() throws ApiException {
        Integer id = null;
        Integer page = null;
        String movementType = null;
        ProductsIdStockHistoryGet200Response response = api.productsIdStockHistoryGet(id, page, movementType);
        // TODO: test validations
    }

    /**
     * Enregistrer un mouvement de stock (admin)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void productsIdStockPostTest() throws ApiException {
        Integer id = null;
        StockInput stockInput = null;
        StockEntry response = api.productsIdStockPost(id, stockInput);
        // TODO: test validations
    }

    /**
     * Spécifications techniques d&#39;un produit
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void productsIdTechnicalSpecsGetTest() throws ApiException {
        Integer id = null;
        TechnicalSpecs response = api.productsIdTechnicalSpecsGet(id);
        // TODO: test validations
    }

    /**
     * Créer ou remplacer les specs techniques (admin)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void productsIdTechnicalSpecsPutTest() throws ApiException {
        Integer id = null;
        TechnicalSpecsInput technicalSpecsInput = null;
        TechnicalSpecs response = api.productsIdTechnicalSpecsPut(id, technicalSpecsInput);
        // TODO: test validations
    }

    /**
     * Créer un produit (admin)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void productsPostTest() throws ApiException {
        ProductInput productInput = null;
        Product response = api.productsPost(productInput);
        // TODO: test validations
    }

}
